### ISSUE TITLE
Cant Create New User

### ISSUE THREAD

**Issue by diorz38** [Laratipsofficial/Ecommerce#2]
OS: Windows 11 64bit
PHP: v813
Node: 16.16

step reproduce:
```
clone repo
cp .env.example .env
touch database\database.sqlite
composer install
php artisan key:generate
php artisan migrate --seed
npm install
npm update
npm run prod
php artisan serve
```
When Super Admin click Add New Button (User/Create)
error:
TypeError: Cannot read properties of undefined (reading '0')    vendor.051f5cb3.js:4

**Comment by diorz38** [comment]
this error appear coz when create new user props.item doest exist.

i can manage to fix this by change file in Pages/User/Create.vue line 37
from:  
`roleId: props.item.roles[0]?.id ?? "", ` 
to:
`roleId: props.item.roles ? props.item.roles[0].id : "",`

**Comment by Laratipsofficial** [comment]
Thanks for the PR. I will check this later this week.

**Comment by tqt97** [comment]
i have same error. Can you fix this

**Comment by Laratipsofficial** [comment]
Thanks for creating an issue for it. It is now solved.
