### ISSUE TITLE
When delete image in Update Product, props.item.images is not update.

### ISSUE THREAD

**Issue by tqt97** [Laratipsofficial/Ecommerce#5]
I try to delete image when update product and props.item.images not update. It will update when i refesh page. Can you review this

**Comment by Laratipsofficial** [comment]
I just checked it. It is working perfectly fine :)

**Comment by tqt97** [comment]
> I just checked it. It is working perfectly fine :)
oke, let me try checked it again. thank

**Comment by tqt97** [comment]
I cloned your source and it have same error. I have add 3 images when update product and save. Then i continue to edit this product and delete 3 images, and i only add 1 images. You can check this case

**Comment by tqt97** [comment]
I add 3 images and save.
Then i edit again.i try to delete 2 image. Notification in drop div image: "You can only upload 2 images" but i only add 1 image.
Other case - i try to delete 3 images.Notification in drop div image: "You can only upload 3 images" but i only add 1 image.
If i refresh this page. everything will be fine.
